export const REQUEST_AUTH = 'REQUEST_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REQUEST_UNSPLASH_PHOTO = 'REQUEST_UNSPLASH_PHOTO';
export const RECEIVE_UNSPLASH_PHOTO = 'RECEIVE_UNSPLASH_PHOTO';
export const REJECT_UNSPLASH_PHOTO = 'REJECT_UNSPLASH_PHOTO';
